package gui;

import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * #Rodrigo de Lima Bispo
 *
 * #Login.java
 */
public class Mensuração extends javax.swing.JFrame {

    /**
     * Creates new form SitesApps
     */
    public Mensuração() {
        initComponents();
        iniciarBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu_superior = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cx10 = new javax.swing.JCheckBox();
        cx1 = new javax.swing.JCheckBox();
        cx2 = new javax.swing.JCheckBox();
        cx3 = new javax.swing.JCheckBox();
        cx4 = new javax.swing.JCheckBox();
        cx5 = new javax.swing.JCheckBox();
        cx6 = new javax.swing.JCheckBox();
        cx7 = new javax.swing.JCheckBox();
        cx8 = new javax.swing.JCheckBox();
        cx9 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remember Why");
        setMinimumSize(new java.awt.Dimension(430, 216));
        setPreferredSize(new java.awt.Dimension(430, 216));
        setResizable(false);
        setSize(new java.awt.Dimension(430, 216));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menu_superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/2.png"))); // NOI18N
        menu_superior.setText("jLabel1");
        getContentPane().add(menu_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 10));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setText("Por favor, selecione abaixo uma nota ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));

        cx10.setText("10");
        cx10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx10ActionPerformed(evt);
            }
        });
        getContentPane().add(cx10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 40, 30));

        cx1.setText("1");
        cx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx1ActionPerformed(evt);
            }
        });
        getContentPane().add(cx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 40, 30));

        cx2.setText("2");
        cx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx2ActionPerformed(evt);
            }
        });
        getContentPane().add(cx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 40, 30));

        cx3.setText("3");
        cx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx3ActionPerformed(evt);
            }
        });
        getContentPane().add(cx3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 40, 30));

        cx4.setText("4");
        cx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx4ActionPerformed(evt);
            }
        });
        getContentPane().add(cx4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 40, 30));

        cx5.setText("5");
        cx5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx5ActionPerformed(evt);
            }
        });
        getContentPane().add(cx5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 40, 30));

        cx6.setText("6");
        cx6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx6ActionPerformed(evt);
            }
        });
        getContentPane().add(cx6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 40, 30));

        cx7.setText("7");
        cx7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx7ActionPerformed(evt);
            }
        });
        getContentPane().add(cx7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 40, 30));

        cx8.setText("8");
        cx8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx8ActionPerformed(evt);
            }
        });
        getContentPane().add(cx8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 40, 30));

        cx9.setText("9");
        cx9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx9ActionPerformed(evt);
            }
        });
        getContentPane().add(cx9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 40, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("de avaliação do sistema:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 110, 30));

        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 100, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx1ActionPerformed
    
      cx2.setSelected(false);
      cx3.setSelected(false);
      cx4.setSelected(false);
      cx5.setSelected(false);
      cx6.setSelected(false);
      cx7.setSelected(false);
      cx8.setSelected(false);
      cx9.setSelected(false);
      cx10.setSelected(false);
      
    }//GEN-LAST:event_cx1ActionPerformed

    private void cx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx2ActionPerformed
      
      cx1.setSelected(false);
      cx3.setSelected(false);
      cx4.setSelected(false);
      cx5.setSelected(false);
      cx6.setSelected(false);
      cx7.setSelected(false);
      cx8.setSelected(false);
      cx9.setSelected(false);
      cx10.setSelected(false);
      
    }//GEN-LAST:event_cx2ActionPerformed

    private void cx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx3ActionPerformed
      
      cx1.setSelected(false);
      cx2.setSelected(false);
      cx4.setSelected(false);
      cx5.setSelected(false);
      cx6.setSelected(false);
      cx7.setSelected(false);
      cx8.setSelected(false);
      cx9.setSelected(false);
      cx10.setSelected(false);
      
    }//GEN-LAST:event_cx3ActionPerformed

    private void cx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx4ActionPerformed
      
      cx1.setSelected(false);
      cx2.setSelected(false);
      cx3.setSelected(false);
      cx5.setSelected(false);
      cx6.setSelected(false);
      cx7.setSelected(false);
      cx8.setSelected(false);
      cx9.setSelected(false);
      cx10.setSelected(false);
      
    }//GEN-LAST:event_cx4ActionPerformed

    private void cx5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx5ActionPerformed
      
      cx1.setSelected(false);
      cx2.setSelected(false);
      cx3.setSelected(false);
      cx4.setSelected(false);
      cx6.setSelected(false);
      cx7.setSelected(false);
      cx8.setSelected(false);
      cx9.setSelected(false);
      cx10.setSelected(false);
      
    }//GEN-LAST:event_cx5ActionPerformed

    private void cx6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx6ActionPerformed
      
      cx1.setSelected(false);
      cx2.setSelected(false);
      cx3.setSelected(false);
      cx4.setSelected(false);
      cx5.setSelected(false);
      cx7.setSelected(false);
      cx8.setSelected(false);
      cx9.setSelected(false);
      cx10.setSelected(false);
      
    }//GEN-LAST:event_cx6ActionPerformed

    private void cx7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx7ActionPerformed
     
      cx1.setSelected(false);
      cx2.setSelected(false);
      cx3.setSelected(false);
      cx4.setSelected(false);
      cx5.setSelected(false);
      cx6.setSelected(false);
      cx8.setSelected(false);
      cx9.setSelected(false);
      cx10.setSelected(false);
      
    }//GEN-LAST:event_cx7ActionPerformed

    private void cx8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx8ActionPerformed
      
      cx1.setSelected(false);
      cx2.setSelected(false);
      cx3.setSelected(false);
      cx4.setSelected(false);
      cx5.setSelected(false);
      cx6.setSelected(false);
      cx7.setSelected(false);
      cx9.setSelected(false);
      cx10.setSelected(false);
    }//GEN-LAST:event_cx8ActionPerformed

    private void cx9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx9ActionPerformed
      
      cx1.setSelected(false);
      cx2.setSelected(false);
      cx3.setSelected(false);
      cx4.setSelected(false);
      cx5.setSelected(false);
      cx6.setSelected(false);
      cx7.setSelected(false);
      cx8.setSelected(false);
      cx10.setSelected(false);
      
    }//GEN-LAST:event_cx9ActionPerformed

    private void cx10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx10ActionPerformed
      
      cx1.setSelected(false);
      cx2.setSelected(false);
      cx3.setSelected(false);
      cx4.setSelected(false);
      cx5.setSelected(false);
      cx6.setSelected(false);
      cx7.setSelected(false);
      cx8.setSelected(false);
      cx9.setSelected(false);
      
    }//GEN-LAST:event_cx10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        if (cx1.isSelected()) {
            String caixa1 = cx1.getText();
            try {
                stmt.executeUpdate("insert into ROOT.MENSURACAO values ('" + caixa1 + "') ");
                JOptionPane.showMessageDialog(this, "Você selecionou a nota 1, obrigado por participar!");
                
        // Volta a tela de login pelo botão "Sair"
        Login1 obj = new Login1();
        obj.setVisible(true);
        dispose();
        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            }
           
        }
        
        if (cx2.isSelected()) {
            String caixa2 = cx2.getText();
            try {
                stmt.executeUpdate("insert into ROOT.MENSURACAO values ('" + caixa2 + "') ");
                JOptionPane.showMessageDialog(this, "Você selecionou a nota 2, obrigado por participar!");
                
        // Volta a tela de login pelo botão "Sair"
        Login1 obj = new Login1();
        obj.setVisible(true);
        dispose();
        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            }
           
        }    
            
         if (cx3.isSelected()) {
            String caixa3 = cx3.getText();
            try {
                stmt.executeUpdate("insert into ROOT.MENSURACAO values ('" + caixa3 + "') ");
                JOptionPane.showMessageDialog(this, "Você selecionou a nota 3, obrigado por participar!");
                
        // Volta a tela de login pelo botão "Sair"
        Login1 obj = new Login1();
        obj.setVisible(true);
        dispose();
        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            }
            
         }
            
        if (cx4.isSelected()) {
            String caixa4 = cx4.getText();
            try {
                stmt.executeUpdate("insert into ROOT.MENSURACAO values ('" + caixa4 + "') ");
                JOptionPane.showMessageDialog(this, "Você selecionou a nota 4, obrigado por participar!");
                
        // Volta a tela de login pelo botão "Sair"
        Login1 obj = new Login1();
        obj.setVisible(true);
        dispose();
        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            }
            
           
        }
            
        if (cx5.isSelected()) {
            String caixa5 = cx5.getText();
            try {
                stmt.executeUpdate("insert into ROOT.MENSURACAO values ('" + caixa5 + "') ");
                JOptionPane.showMessageDialog(this, "Você selecionou a nota 5, obrigado por participar!");
                
        // Volta a tela de login pelo botão "Sair"
        Login1 obj = new Login1();
        obj.setVisible(true);
        dispose();
        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            }    
            
        }  
        
        if (cx6.isSelected()) {
            String caixa6 = cx6.getText();
            try {
                stmt.executeUpdate("insert into ROOT.MENSURACAO values ('" + caixa6 + "') ");
                JOptionPane.showMessageDialog(this, "Você selecionou a nota 6, obrigado por participar!");
                
        // Volta a tela de login pelo botão "Sair"
        Login1 obj = new Login1();
        obj.setVisible(true);
        dispose();
        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            }  
            
        }
            
        if (cx7.isSelected()) {
            String caixa7 = cx7.getText();
            try {
                stmt.executeUpdate("insert into ROOT.MENSURACAO values ('" + caixa7 + "') ");
                JOptionPane.showMessageDialog(this, "Você selecionou a nota 7, obrigado por participar!");
                
        // Volta a tela de login pelo botão "Sair"
        Login1 obj = new Login1();
        obj.setVisible(true);
        dispose();
        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            } 
            
        }
            
        if (cx8.isSelected()) {
            String caixa8 = cx8.getText();
            try {
                stmt.executeUpdate("insert into ROOT.MENSURACAO values ('" + caixa8 + "') ");
                JOptionPane.showMessageDialog(this, "Você selecionou a nota 8, obrigado por participar!");
                
        // Volta a tela de login pelo botão "Sair"
        Login1 obj = new Login1();
        obj.setVisible(true);
        dispose();
        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            }
            
        }
           
        if (cx9.isSelected()) {
            String caixa9 = cx9.getText();
            try {
                stmt.executeUpdate("insert into ROOT.MENSURACAO values ('" + caixa9 + "') ");
                JOptionPane.showMessageDialog(this, "Você selecionou a nota 9, obrigado por participar!");
                
        // Volta a tela de login pelo botão "Sair"
        Login1 obj = new Login1();
        obj.setVisible(true);
        dispose();
        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            }
            
        } 
        
        if (cx10.isSelected()) {
            String caixa10 = cx10.getText();
            try {
                stmt.executeUpdate("insert into ROOT.MENSURACAO values ('" + caixa10 + "') ");
                JOptionPane.showMessageDialog(this, "Você selecionou a nota 10, obrigado por participar!");
                
        // Volta a tela de login pelo botão "Sair"
        Login1 obj = new Login1();
        obj.setVisible(true);
        dispose();
        
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            }
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        // Volta a tela de login pelo botão "Sair"
        Login1 obj = new Login1();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mensuração.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mensuração.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mensuração.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mensuração.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mensuração().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cx1;
    private javax.swing.JCheckBox cx10;
    private javax.swing.JCheckBox cx2;
    private javax.swing.JCheckBox cx3;
    private javax.swing.JCheckBox cx4;
    private javax.swing.JCheckBox cx5;
    private javax.swing.JCheckBox cx6;
    private javax.swing.JCheckBox cx7;
    private javax.swing.JCheckBox cx8;
    private javax.swing.JCheckBox cx9;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menu_superior;
    // End of variables declaration//GEN-END:variables

    // Declarar variáveis de Conexão, Statement e ResultSet para conexão com o banco de dados
    private java.sql.Connection con;
    private java.sql.Statement stmt;

    
    private void iniciarBD() {
        
        // Circundar Instrução com try-catch quando existe conexão com o banco de dados
        try {
            // Carregar driver da biblioteca "derbyclient.jar"
            Class.forName("org.apache.derby.jdbc.ClientDriver");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }

        // Conexão do banco de dados bd na porta 1527
        String url = "jdbc:derby://localhost:1527/bd";
        // String com usuário do banco de dados
        String user = "root";
        // String com senha do banco de dados
        String pass = "@Acesso2018";

        try {
            // Variável de conexão com recebe dados do banco, usuário, senha e inicia Statement para instruções
            con = DriverManager.getConnection(url, user, pass);
            // Variáveis de Statement recebe variável de Conexão com propriedades do ResultSet
            stmt = con.createStatement();
            // Variáveis ResultSet recebem a instrução select das tabelas siteapps e bancos por meio do Statement
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());

        }
        
    }
}
